---

##### PROJECT NAME AND LOCATION
# project
EE_ID :  YOURPROJECT
Project : DublinBay
NatureROI : Transects


# HPC or local use (fill with HPC is using shoreliner on CNES HPC, local otherwise)
typeUse : local

#transects path (transects in EPSG:4326)
PathTransect : transects_Dublin.p

###transects creation
CreateTransects : False
#Coordonates of N>=4 points to define the ROI
ROI_array : [[-6.10,53.39],[-6.18,53.39],[-6.18,53.34],[-6.10,53.34]]#[[-1.95,43.45],[-1.95,43.25],[-1.7,43.25],[-1.7,43.45]]#
#Transect length in km
Length_transect : 1
#Approximate inter-transects distance in km
Inter_transect : 0.1
#Path to source wl shapefile
Shapefile_path : /DataShorelines/gshhg_shp/GSHHS_shp/h/GSHHS_h_L1.shp
#transects path (transects in EPSG:4326)
NewPathTransect : transects_projectname.p

##### USER-DEFINED INPUTS
# Features to detect
Waterline : True
SandBar : False
Vegetation : False

# Download also RGB images (for qualitative validation)
RGB : False

# Download WL.shp and TR.shp to see it on QGIS
WLshp : True
TRshp : True

#ROIs
SizeROI : 0.04   #approximate ROIs size (in degrees 1° ~ 100km)
SaveShpROI : True

# starting and ending dates (YYYY/MM/DD)
Dates:
    - 2023/09/01
    - 2023/09/30

# satellite missions wanted
Missions:
    - S2


#Clouds
MaxCloudCover : 50
PeakNoiseFilter : True
PeakNoiseFilterRatio : 5

# WATERLINE INDEX band combination used : SCoWI, NDWI, AWEIns, MNDWI, AWEIsh, etc...
WaterlineIndex: SCoWI

##### METHODOLOGY
# preprocessing : Pansharpening, CloudMasking_Landsat, CloudMasking_Sentinel2
Preprocessing:
    - Bicubic

# contouring method used : Otsu, RefOtsu, MSV, WP
Contouring : RefOtsu

# outlier correction : IQR
Postprocessing :
    - IQR


